using System;
using Microsoft.EntityFrameworkCore;
using ShipmentPackerDAL.Entities;

namespace ShipmentPackerDAL.Context
{
    public class MyDBContext : DbContext
    {
        static DbContextOptions<MyDBContext> options =
            new DbContextOptionsBuilder<MyDBContext>()
            .UseInMemoryDatabase("TheDB")
                .Options;

        //For Local host
        public MyDBContext() : base(options)
        {

        }

        //For Azure Deployment
        /*protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
                optionsBuilder.UseSqlServer("Insert ConnectionsString here generated by Azure");
            }
        }*/

        public DbSet<Project> Projects { get; set; }
        //public DbSet<PackingList> PackingLists { get; set; }
   }
}
